/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Paulo Henrique
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    public Estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstoque = new javax.swing.JTable();
        jButtonDeletarProduto = new javax.swing.JButton();
        jButtonConsultarProduto = new javax.swing.JButton();
        jButtonRetirarProduto = new javax.swing.JButton();
        jButtonCadastrarProduto = new javax.swing.JButton();
        jLabelFundoPreto = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Validade", "Quantidade", "Valor Bruto", "Valor Liquido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEstoque);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 1060, 610));

        jButtonDeletarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonDeletarProduto.setText("Deletar Produto");
        jButtonDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 880, 220, 60));

        jButtonConsultarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonConsultarProduto.setText("Consultar Produto");
        jButtonConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 880, 220, 60));

        jButtonRetirarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRetirarProduto.setText("Retirar Produto");
        jButtonRetirarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRetirarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 880, 220, 60));

        jButtonCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCadastrarProduto.setText("Cadastrar Produto");
        jButtonCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 880, 220, 60));

        jLabelFundoPreto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View.imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoPreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1600, 1170));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View.imagens/LeaoBackGround.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarProdutoActionPerformed

    private void jButtonRetirarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRetirarProdutoActionPerformed

    private void jButtonConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarProdutoActionPerformed

    private void jButtonDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeletarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarProduto;
    private javax.swing.JButton jButtonConsultarProduto;
    private javax.swing.JButton jButtonDeletarProduto;
    private javax.swing.JButton jButtonRetirarProduto;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundoPreto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEstoque;
    // End of variables declaration//GEN-END:variables
}
